### ISSUE TITLE
Cloudflare issue

### ISSUE THREAD

**Issue by Laande** [UnfamiliarLegacy/G-Earth#1]
On some retro using cloudflare and for somes users, when you press connect on g-earth, cloudflare will block the request and load indefinitely using all of your cpu

Example of retro :
- habba.io
- habden.co.uk
- habba.io

Video :
https://discord.com/channels/744927320871010404/744930901204402339/1199343288793182299

**Comment by UnfamiliarLegacy** [comment]
Cloudflare turnstile is failing and I don't know why. Most likely the mitm proxy modifies the http(s) requests in such a way that cloudflare is not happy about it.

**Comment by Kakashi00xd** [comment]
Any updates on this, Mike?

**Comment by xAstroBoy** [comment]
yeah now is happening on bsshotel as well.

**Comment by AbandonedAccount1111** [comment]
Is happening on a retro i play as well now

**Comment by technicaln3rd** [comment]
perhaps headless mode could work (or its certificate pinning)
or dns based byoassing

**Comment by UnfamiliarLegacy** [comment]
Fixed.
